### ISSUE TITLE
Create a Basic Achievements Page

### ISSUE THREAD

**Issue by danvolchek** [mihaivavram/work-life-balance-nudger#19]

**Comment by mihaivavram** [comment]
The format of the data for @danvolchek love :cherries: :

We probably only want 4 weeks back from the request call for now. And each week should be from Sunday to Sunday.

Where data is sorted in reverse chronological order e.g. `<date1>` is the most recent week (first in json response) from our point of view (week prior to this week), and `<date2>` is the week before that, etc...

`<date1>` should be the last day of last week, so if today is `04/03/2019`, then the last day of last week is `03/31/2019` (last Sunday).

You can check today's date using Python functions when I make the call to discern this.

```json
	data: {
		"03-31-2019": {
			"startDate":"02-24-2019",
			"endDate":"03-31-2019",
			"accomplishments":{
				"health":{
					"scheduled":4,
					"completed":2
				},
				"productivity":{
					"..."
				},
				"happiness":{
				       "..."
				}
			}		
		},
		"<date2>": {
			"..."
		},
		"<date3>": {
			"..."
		},
		"<date4>": {
			"..."
		}
	}
```

Also feel free to change this in any way and return an array instead of objects of objects or even change the format if you wish, just keep me updated with that. Ideally sooner than later so that I don't have to redo the work from the front-end.

**Comment by danvolchek** [comment]
@mihaivavram The endpoint is at `/wlbnudgerapi/achievements` and a sample response looks like this:

```js
[
  {
    "startDate":"02-24-2019",
    "endDate":"03-31-2019",
    "categories": {
      "Health": {
        "scheduled": 4,
        "completed": 2
      },
      "Happiness": {
	"scheduled": 4,
        "completed": 2
      },
      "Productivity": {
	"scheduled": 4,
        "completed": 2
      }
    }
  }
  //more objects of the same form
]
```
Some nots on what's returned:
  * Entries in the list will be in reverse-chronological order.
  * Currently there are always four entries (the past four weeks).

Some notes on how this is generated (not relevant to displaying this info):
  * The start date is inclusive while the end date is exclusive.
  * The weeks start from the first Sunday of the previous week (`current day - 7 - (#of days needed to get to Sunday or 0 if current day is Sunday)`). I feel like this makes the most sense.

Some thoughts on what to display (for the future):
  * I think there is some value in including the current week in the stats (i.e. this week so far) (i.e. no `-7`) - let me know what you think.

 Let me know if there should be any changes!

**Comment by danvolchek** [comment]
There was a typo in the `endDate` value in the example - the month was `03` instead of `02`. I fixed it now. There will always be 7 days between the `startDate` and `endDate`.

**Comment by mihaivavram** [comment]
@danvolchek I like this schema! I also understand and agree with your logic. Yes, indeed it would be nice to show the current week in the stats, but I think it is an icing on the cake issue.

In an ideal world, the user should be able to toggle between different temporal groupings e.g. daily, weekly, monthly, yearly, etc...

But let us get there when we get there. For the next few weeks, this is perfect.

Thank you!

**Comment by mihaivavram** [comment]
Completed, closing.
