### ISSUE TITLE
Create description/link actual data

### ISSUE THREAD

**Issue by mihaivavram** [mihaivavram/work-life-balance-nudger#43]

**Comment by mihaivavram** [comment]
See #27 for the links.

**Comment by danvolchek** [comment]
I had some free time so I implemented sleep, exercise, play, and breaks.

Some things to do:
  * It's not connected to Zuyi's code in the nudge API.
  * I left out social interaction. After a more in depth reading of the links, I didn't like what they presented. The why article seemed to scare people into making friends (otherwise you die sooner, have higher risk of disease, etc) which I don't think is constructive.

Most importantly:
  * Someone else definitely needs to take a look at these and reword them if needed or confirm that they're okay.

**Comment by danvolchek** [comment]
Work related to this added to #47.
