### ISSUE TITLE
Look at Description/Links content, validate it, and add valid descriptions/links for social interaction

### ISSUE THREAD

**Issue by mihaivavram** [mihaivavram/work-life-balance-nudger#47]

**Comment by danvolchek** [comment]
Some things to do:
 - I left out social interaction. After a more in depth reading of the links, I didn't like what they presented. The why article seemed to scare people into making friends (otherwise you die sooner, have higher risk of disease, etc) which I don't think is constructive.

Most importantly:
    - Someone else definitely needs to take a look at these and reword them if needed or confirm that they're okay.
    - We need to make sure that we'd be okay with presenting the reasons/articles in class - that the information they present is solid/backed up by research/not just opinions.

**Comment by mihaivavram** [comment]
Completed, closing.
